Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/07/2024
Var
// Seção de Declarações das variáveis 
numero, par, impar: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva um número")
leia(numero)
  se numero %2 = 0 entao
  escreval("Seu número é par")
  senao
  escreval("Seu número é impar")
fimse
Fimalgoritmo